export const products = [
  // Tiramisu Cakes
  {
    id: 'classic-tiramisu',
    name: 'Classic Tiramisu',
    description: 'Traditional Italian tiramisu with rich mascarpone cream and espresso-soaked ladyfingers',
    price: 120,
    category: 'cake',
    image: '/products/classic-tiramisu.png',
    available: true,
    sortOrder: 1,
  },
  {
    id: 'biscoff-tiramisu',
    name: 'Biscoff Tiramisu',
    description: 'Decadent tiramisu layered with creamy mascarpone, Biscoff cookie spread and crumbles',
    price: 120,
    category: 'cake',
    image: '/products/biscoff-tiramisu.png',
    available: true,
    sortOrder: 2,
  },
  {
    id: 'oreo-tiramisu',
    name: 'Oreo Tiramisu',
    description: 'Delicious cookies & cream tiramisu with crushed Oreos and rich dark chocolate drizzle',
    price: 120,
    category: 'cake',
    image: '/products/oreo-tiramisu.png',
    available: true,
    sortOrder: 3,
  },
  // Milkshakes
  {
    id: 'classic-vanilla',
    name: 'Classic Vanilla',
    description: 'Smooth and creamy vanilla milkshake made with real vanilla bean',
    price: 39,
    category: 'milkshake',
    image: '/products/classic-vanilla.png',
    available: true,
    sortOrder: 4,
  },
  {
    id: 'chocolate-overload',
    name: 'Chocolate Overload',
    description: 'Rich and indulgent chocolate milkshake with premium cocoa',
    price: 39,
    category: 'milkshake',
    image: '/products/chocolate-overload.png',
    available: true,
    sortOrder: 5,
  },
  {
    id: 'strawberry-bliss',
    name: 'Strawberry Bliss',
    description: 'Fresh and fruity strawberry milkshake bursting with berry flavor',
    price: 39,
    category: 'milkshake',
    image: '/products/strawberry-bliss.png',
    available: true,
    sortOrder: 6,
  },
  {
    id: 'matcha-latte',
    name: 'Matcha Latte',
    description: 'Earthy and smooth matcha green tea milkshake with a hint of sweetness',
    price: 39,
    category: 'milkshake',
    image: '/products/matcha-latte.png',
    available: true,
    sortOrder: 7,
  },
  {
    id: 'cookies-and-cream',
    name: 'Cookies & Cream',
    description: 'Crunchy cookie pieces blended into a creamy vanilla milkshake',
    price: 39,
    category: 'milkshake',
    image: '/products/cookies-and-cream.png',
    available: true,
    sortOrder: 8,
  },
];
